spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: create-drop
        default_batch_fetch_size: 100
  config:
    import: application-secret.yml
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      hibernate:
        SQL: debug
redisson:
  single-server-config:
    address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
#    root: debug
#        type.descriptor.sql: trace
#        orm.jdbc.bind: trace