spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: create-drop
        default_batch_fetch_size: 100

    open-in-view: false
  config:
    import: application-secret.yml
logging:
  level:
    org:
      hibernate:
        SQL: debug
#    root: debug
#        type.descriptor.sql: trace
#        orm.jdbc.bind: trace