spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  data:
    redis:
      repositories:
        enabled: false
      host: ${AWS_REDIS_HOST}
      port: 6379
logging:
  level:
    org:
      hibernate:
        SQL: debug
redisson:
  single-server-config:
    address: redis://${spring.data.redis.host}:${spring.data.redis.port}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    stack:
      auto: false
auth:
  jwt:
    issuer: BeanSpace
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: ${JWT_EXPIRATION_HOUR}
oauth2:
  kakao:
    client_id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect_url: ${OAUTH_KAKAO_REDIRECT_URL}
    auth_server_base_url: "https://kauth.kakao.com"
    resource_server_base_url: "https://kapi.kakao.com"